[package]
name = "csc443-project"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145" }
bincode = "1.3"
libc = "0.2.176"

[[bin]]
name = "tests"
path = "src/tests.rs"

[[bin]]
name = "experiments"
path = "src/experiments.rs"

[features]
default = []
mock = []

[dev-dependencies]
proptest = "1.8.0"
